//
// Created by andreasbuhr on 10.01.21.
//

#ifndef QPROPERTY_PERFORMANCE_REPORT_PROPERTY_MEMORY_MEASUREMENT_H
#define QPROPERTY_PERFORMANCE_REPORT_PROPERTY_MEMORY_MEASUREMENT_H

void print_newbinding_memusage();

#endif //QPROPERTY_PERFORMANCE_REPORT_PROPERTY_MEMORY_MEASUREMENT_H
